apiVersion: apps/v1
kind: Deployment
metadata:
    name: "techtestapp"
spec:
    selector:
        matchlabels:
            app: "techtestapp"
        replicas: 5
        template:
            metadata:
                labels:
                    app: "techtestapp"
            spec:
                containers:
                - image: infra/src
                  imagePullPolicy: Always
                  name: "techtestapp"
                  ports:
                  - containerPort: 80